services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ../compendium-data/data.db:/app/var/data.db:z
      - ../compendium-data/caddy:/data:Z
    env_file:
      - .env.prod
  worker:
    build: .
    restart: unless-stopped
    command: frankenphp php-cli bin/console messenger:consume async --time-limit=3600
    volumes:
      - ../compendium-data/data.db:/app/var/data.db:z
    env_file:
      - .env.prod